# Generated by Django 4.2.4 on 2023-08-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomnumbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomnumber',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
